/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro.universidad.vistas;

import Datas.AlumnoData;
import Datas.CursadaData;
import Datas.MateriaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import pro.universidad.modelo.Alumno;
import pro.universidad.modelo.Conexion;
import pro.universidad.modelo.Cursada;
import pro.universidad.modelo.Materia;

/**
 *
 * @author Jannete
 */
public class VistaNotas extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private ArrayList<Cursada> listCursadas;
    private ArrayList<Materia> listMaterias;
    private CursadaData cd;
    private MateriaData md;
    private AlumnoData ad;
    private ArrayList<Alumno> listAlumnos;
    private Conexion conexion;
    /**
     * Creates new form VistaNotas
     */
    public VistaNotas() {
        initComponents();
        
        try {
            conexion= new Conexion();
            modelo = new DefaultTableModel();
            cd = new CursadaData(conexion);
            listCursadas = (ArrayList)cd.obtenerCursadas();
            md=new MateriaData(conexion);
            listMaterias= (ArrayList)md.obtenerMaterias();
            ad = new AlumnoData(conexion);
            listAlumnos = (ArrayList)ad.obtenerAlumnos();
            
            cargarAlumnos();
            armarCabeceraTabla();
            cargarDatos();
            
            
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAlumnosMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAlumnos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMaterias = new javax.swing.JTable();
        botonGuar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("CARGA DE NOTAS");

        jLabel2.setText("ALUMNO");

        cbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnosActionPerformed(evt);
            }
        });

        tMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tMaterias.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tMateriasPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tMaterias);

        botonGuar.setText("GUARDAR");
        botonGuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuarActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Seleccionar celda de NOTA a modificar, hacer \"Enter\" y  despues \"Guardar\"");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botonGuar)
                        .addGap(62, 62, 62)
                        .addComponent(botonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuar)
                    .addComponent(botonSalir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
       dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void cbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnosActionPerformed

        cargarDatos();
    }//GEN-LAST:event_cbAlumnosActionPerformed

    private void botonGuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuarActionPerformed
        
        Alumno al = (Alumno)cbAlumnos.getSelectedItem();
        
        int idMateria = Integer.parseInt(tMaterias.getValueAt(tMaterias.getSelectedRow(), 0).toString());
        
        float nota = Float.parseFloat(tMaterias.getValueAt(tMaterias.getSelectedRow(), 2).toString());
        
        System.out.println("idAlumno "+ al.getIdAlumno()+" idMateria "+ idMateria+" Nota " +nota);
        cd.actualizarNotaCursada(al.getIdAlumno(), idMateria, nota );
    }//GEN-LAST:event_botonGuarActionPerformed

    private void tMateriasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tMateriasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tMateriasPropertyChange

    public void cargarAlumnos(){
        for(Alumno a: listAlumnos){
            
            cbAlumnos.addItem(a);
        }
    }
    public void armarCabeceraTabla(){
        ArrayList<Object>columns=new ArrayList<Object>();//se agregan los titulos de las columnas
        
        columns.add("ID");
        columns.add("Materia");
        columns.add("Nota");
        
        for(Object it:columns){
            modelo.addColumn(it);
        }
        tMaterias.setModel(modelo);//aca viene el modelo que arme
    }
    
    public void borrarFilasTabla(){//Para mostrar datos nuevos
        int a = modelo.getRowCount()-1;
        for(int i=a; i>=0 ;i--){
            
            modelo.removeRow(i);
        }
    }
    
    public void cargarDatos(){
        
        borrarFilasTabla();
        
        Alumno al = (Alumno)cbAlumnos.getSelectedItem();
        
        for(Cursada a:listCursadas){
            
            if(a.getAlumno().getIdAlumno()==al.getIdAlumno()){
                
                modelo.addRow(new Object []{a.getMateria().getIdMateria(),a.getMateria().getNombre(),a.getNota()});
                
                
            }
    }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<Alumno> cbAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tMaterias;
    // End of variables declaration//GEN-END:variables
}
